Generate WorkerTypes.cs from json
spatialos/gdk-for-unity pull request #1504
Opened 2021-01-25 14:58 UTC by paulbalaji

- [x] moved the worker type extraction to `DetailsStore`
- [x] updated worker menu generator to read types from `DetailsStore`
- [x] added generator for `WorkerTypes` class
- [x] updated playground to use `WorkerTypes`

#### Tests

- [x] generate code
- [x] run playground

#### Documentation

- [ ] changelog

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

2021-01-25 15:06 UTC, jamiebrynes7 commented on workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
> +            Logger.Trace($"Found {workerTypes.Count} worker types:\n - {string.Join("\n - ", workerTypes)}");
Do you know why we did this rather than pattern matching against the file name?

2021-01-25 15:06 UTC, zeroZshadow requested changes

2021-01-25 15:06 UTC, zeroZshadow commented on workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
> +using NLog;
Why does this suddenly need NLog?

2021-01-26 11:25 UTC, paulbalaji commented on workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
> +                if (!match.Success)
Might be worth logging a warning here if we match a worker json but can't get a worker type out of it

2021-01-26 11:40 UTC, jamiebrynes7 approved these changes

2021-01-26 13:10 UTC, zeroZshadow approved these changes

2021-01-26 14:12 UTC, merged